### ISSUE TITLE
Suggestion if possible: frame alpha settings (combat settings too)

### ISSUE THREAD

**Issue by ceylina** [SharpWoW/BodyguardHealth#19]
Would be great to be able to set the alpha on the entire frame. It's not in invasive frame at all but would love to be able t o say have it at 50% opacity or even better yet, set opacity out of combat and 100% in combat ;)

**Comment by Sharparam** [comment]
Good idea. I'll look into implementing this during the coming week.

**Comment by Sharparam** [comment]
Added new options for controlling the opacity (optionally with a different opacity in combat) under Frame settings -> Other.

I'll push a release and it should be available from Curse/WoWI shortly!
